---
apiVersion: kaas.mirantis.com/v1alpha1
kind: MetalLBConfig
metadata:
  labels:
    kaas.mirantis.com/provider: baremetal
    kaas.mirantis.com/region: region-one
    cluster.sigs.k8s.io/cluster-name: SET_NAMESPACE
  name: mosk-metallb-config
  namespace: SET_NAMESPACE
spec:
  ipAddressPools:
  - name: services
    spec:
      addresses:
      - 192.168.123.121-192.168.123.149
      autoAssign: true
      avoidBuggyIPs: false
  l2Advertisements:
  - name: services
    spec:
      ipAddressPools:
      - services
      interfaces:
      - k8s-lcm
