apiVersion: ipam.mirantis.com/v1alpha1
kind: L2Template
metadata:
  labels:
    ipam/Cluster: kaas-CHILD_NAMESPACE
    kaas.mirantis.com/provider: baremetal
    kaas.mirantis.com/region: region-one
  name: CHILD_NAMESPACE-2nic
  namespace: CHILD_NAMESPACE
spec:
  clusterRef: kaas-CHILD_NAMESPACE
  autoIfMappingPrio:
  - provision
  - ens
  - eno
  - enp
  npTemplate: |-
    version: 2
    ethernets:
      {{nic 0}}:
        dhcp4: false
        dhcp6: false
        addresses:
          - {{ip "0:master-region-one"}}
        gateway4: {{gateway_from_subnet "master-region-one"}}
        nameservers:
          addresses: {{nameservers_from_subnet "master-region-one"}}
        match:
          macaddress: {{mac 0}}
        set-name: {{nic 0}}
        mtu: 1500
      {{nic 1}}:
        dhcp4: false
        dhcp6: false
        match:
          macaddress: {{mac 1}}
        set-name: {{nic 1}}
        mtu: 9000
      {{nic 2}}:
        dhcp4: false
        dhcp6: false
        match:
          macaddress: {{mac 2}}
        set-name: {{nic 2}}
        mtu: 9000
    bonds:
      bond0:
        interfaces:
          - {{nic 1}}
          - {{nic 2}}
        parameters:
          mode: 802.3ad
        mtu: 9000
    vlans:
      pr-floating:
        id: 464
        link: bond0
      tenant:
        id: 465
        link: bond0
        addresses:
          - {{ip "tenant:tenant"}}
        mtu: 9000
      stor-frontend:
        id: 462
        link: bond0
        addresses:
          - {{ip "stor-frontend:storage-frontend"}}
        mtu: 9000
      stor-backend:
        id: 463
        link: bond0
        addresses:
          - {{ip "stor-backend:storage-backend"}}
        mtu: 9000
