---
apiVersion: ipam.mirantis.com/v1alpha1
kind: Subnet
metadata:
  labels:
    kaas.mirantis.com/provider: baremetal
    kaas.mirantis.com/region: region-one
  name: storage-backend
  namespace: CHILD_NAMESPACE
spec:
  cidr: 10.11.0.0/24
  includeRanges:
  - 10.11.0.10-10.11.0.200
---
apiVersion: ipam.mirantis.com/v1alpha1
kind: Subnet
metadata:
  labels:
    kaas.mirantis.com/provider: baremetal
    kaas.mirantis.com/region: region-one
  name: storage-frontend
  namespace: CHILD_NAMESPACE
spec:
  cidr: 10.12.0.0/24
  includeRanges:
  - 10.12.0.10-10.12.0.200

---
apiVersion: ipam.mirantis.com/v1alpha1
kind: Subnet
metadata:
  labels:
    kaas.mirantis.com/provider: baremetal
    kaas.mirantis.com/region: region-one
  name: tenant
  namespace: CHILD_NAMESPACE
spec:
  cidr: 10.13.0.0/24
  includeRanges:
  - 10.13.0.10-10.13.0.200
